---
- name: Installing python3 and docker
  hosts: worker
  become: yes
  tasks:
  - name: Installing python3 and docker
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
        - python3
        - docker
      update_cache: yes
      state: present

- name: start docker daemond
  hosts: worker
  become: true
  tasks:
  - name: Starting docker daemond
    systemd: 
      name: docker 
      state: started

- name: change sock perm
  hosts: worker
  become: true
  tasks:
  - name: change sock perm
    command: chmod 666 /var/run/docker.sock                    


- name: Running docker image
  hosts: worker
  become: true
  tasks:
  - name: Running docker image
    command: docker run -d -p 5000:5000 esso4real/python-app:v1              